version: "3"

services:
  app:
    #    user: $UID:$GID
    build:
      context: .
    ports:
      - "8085:8085"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8085"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgress
      - DB_PASS=secretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRESS_DB=app
      - POSTGRESS_USER=postgres
      - POSTGRESS_PASSWORD=secretpassword
